server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://182.92.115.193:3306/bookstore?serverTimezone=UTC
    username: root
    password: mysql123456
mybatis:
  type-aliases-package: com.bjtu.book_shop_rear.entity
  mapper-locations: classpath:mybatis/dao/*.xml
